# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-05 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='test',
            new_name='text',
        ),
    ]
